language: node_js

node_js:
  - 6

install:
  - npm i

script:
  ## now run cypress headlessly
  ## and record all of the tests.
  ## Cypress will search for a
  ## CYPRESS_RECORD_KEY environment
  ## variable by default and apply
  ## this to the run.
  - npm run eslint
  - npm run cypress:run
