language: node_js
node_js:
  - 10
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
script:
  - npm run eslint
  - $(npm bin)/cypress run --browser chrome --record --key cc2b3d4b-8813-4231-9a5d-f32ad216ebfb