language: node_js

node_js:
  - 6

## Cache folders with installed NPM modules
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.npm
    - node_modules

install:
  - npm i

script:
  ## now run cypress headlessly
  ## and record all of the tests.
  ## Cypress will search for a
  ## CYPRESS_RECORD_KEY environment
  ## variable by default and apply
  ## this to the run.
  - npm run cypress:run -- --record --key cc2b3d4b-8813-4231-9a5d-f32ad216ebfb